name: Ecommerce-API Scheduled Tests

on:
  schedule:
    - cron: "30 1 * * *" # every day at 2:30AM UTC

permissions:
  contents: write
  pages: write
  id-token: write
  issues: write

jobs:
  EcommerceAPITest:
    uses: ./.github/workflows/basePipeline.yml
    with:
      THREADS: 1
      ENV: prod
      ALLURE_REPORT_NAME: Ecommerce-API Regression
      ALLURE_REPORT_DEPLOY_FOLDER: Ecommerce_API_Regression_Tests
      TEST_SUITE: testng.xml
      SEND_EMAIL: 'true'
      EMAIL_TITLE: Ecommerce-API Regression Test Report
      RERUN_FAILED_TESTS: 'true'
    secrets: inherit